---
project: "/Developer Program"
name: developer-program
github:
- 18F/API-All-the-X
description: The /Developer program provides comprehensive support and resources for any federal agency engaged in the production or use of APIs. 
partners:
- General Services Administration
stage: live
impact: "Helps federal agencies develop useful, robust APIs through educational resource and tools. The program has served over 70 agencies, including each cabinet department, the National Archives, the Federal Communications Commission, the Consumer Financial Protection Bureau, and the Office of Personnel Management."
tagline: "We're helping federal agencies develop useful and robust APIs."
tags: 
- education
- evangelism
- api
milestones:
- 'January 2014: 18F began work on project'
- 'May 2014: API Usability Program Launched'
- 'May 2014: /Developer Program Website v2.0 Announced'
- 'September 2014: 20th API Usability Participant'
contact:
- gray.brooks@gsa.gov
stack: 
team: gray
licenses:
  API-All-the-X: Public Domain (CC0)
licenseBranch:
  API-All-the-X: gh-pages
links:
- https://pages.18f.gov/API-All-the-X/
- https://18f.gsa.gov/2014/05/29/announcing-the-developer-program-a-new-hub-for/
blog:
- "/developer"
status: 
