# 
# This is the main data file for your project.  Change the values
# below accordingly.
# See http://yaml.org for details about YAML
#
org_name:  18F
org_abbrev: 18F
address:
 street: 1800 F Street NW
 suite: 
 city: Washington
 state: D.C.
 zip: 20000
point_of_contact: 18F
# A valid HREF--email, form, etc.
poc_link: http://18f.gsa.gov
poc_phone: 123-123-1234
sponsoring_office: General Services Administration
logo_url: /assets/img/usa_logo.png
home_url: index.html

