# 
# This is the main data file for your project.  Change the values
# below accordingly.
# See http://yaml.org for details about YAML
#
org_name:  YOUR ORGANIZATION NAME
org_abbrev: YON
address:
 street: 1000 Main Street
 suite: 
 city: Washington
 state: D.C.
 zip: 20000
point_of_contact: Thomas Jefferson 
# A valid HREF--email, form, etc.
poc_link: mailto:tj@monticello.gov
poc_phone: 123-123-1234
sponsoring_office: Office of the Chief Information Officer
logo_url: /assets/img/USA_flag_icon.png
home_url: index.html

